const path = require('path')
const fs   = require('fs')

const directories = [
  '../src/Components/Atoms',
  '../src/Components/Molecules',
  '../src/Components/Organisms',
  '../src/Components/Templates',
  '../src/Components/Pages'
]

// Hold all data that should be included later.
let data = [[], [], [], [], []]
directories.forEach((dir, i) => {
  const dirPath = path.join(__dirname, dir)
  const files = fs.readdirSync(dirPath) 

  files.forEach((name) => {
    const file = path.join(dirPath, name)
    const stats = fs.statSync(file)
    
    if ( ! stats.isDirectory() ) {
      return
    }

    const exampleFile = path.join(file, 'example.js')
    if ( fs.existsSync(exampleFile) ) {
      data[i].push(name)
    } 
  })
})

// The folders for a respective file.
const folders = [ 'Atoms', 'Molecules', 'Organisms', 'Templates', 'Pages' ]

// Build the include definitions from the data object.
let includes = []
data.forEach((array, i) => array.forEach((name) => {
  const folder = folders[i]
  includes.push(`import ${name}, { title as title${name} } from './Components/${folder}/${name}/example'`)
}))
includes = includes.join("\n")

// update the data arrays to strings.
data = data.map((array, index) => {
  let strs = [];
  array.forEach((name) => {
    strs.push(`{ component: ${name}, title: title${name} }`)
  })
  return '[ ' + strs.join("\n             , ") + ' ]'
})

// Create the file's actual appearence.
const file = `
import React from 'react'
import { render } from 'react-dom'
import { AppContainer } from 'react-hot-loader'

/* Import files relevant to the contianer */
import StyleGuideContainer from './Components/Pages/StyleGuide'

/*  -- GENERATED BY GEN_DOC -- */
${includes}

const data = {
  atoms:     ${data[0]},
  molecules: ${data[1]},
  organisms: ${data[2]},
  templates: ${data[3]},
  pages:     ${data[4]}
}

const app = (
  <AppContainer>
    <StyleGuideContainer {...data} />
  </AppContainer>
)
render(app, document.querySelector('#app'))
`

// Write the file.
fs.writeFileSync(path.join(__dirname, '../src/styleguide.js'), file)

console.log('Success!')
