
import React from 'react'
import { render } from 'react-dom'
import { AppContainer } from 'react-hot-loader'

/* Import files relevant to the contianer */
import StyleGuideContainer from './Components/Pages/StyleGuide'

/*  -- GENERATED BY GEN_DOC -- */
import Button, { title as titleButton } from './Components/Atoms/Button/example'
import ColorWell, { title as titleColorWell } from './Components/Atoms/ColorWell/example'
import ColorPicker, { title as titleColorPicker } from './Components/Molecules/ColorPicker/example'

const data = {
  atoms:     [ { component: Button, title: titleButton }
             , { component: ColorWell, title: titleColorWell } ],
  molecules: [ { component: ColorPicker, title: titleColorPicker } ],
  organisms: [  ],
  templates: [  ],
  pages:     [  ]
}

const app = (
  <AppContainer>
    <StyleGuideContainer {...data} />
  </AppContainer>
)
render(app, document.querySelector('#app'))
